Завдання 1.

1. Створіть одновимірний масив (вектор) з останніми 10-ма натуральними числами та виведіть його значення.

In [1]:
import numpy as np

In [2]:
array = np.arange(1, 10)
print(array)

[1 2 3 4 5 6 7 8 9]


Завдання 2

1. Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та виведіть його значення.


In [3]:
from random import randint

matrix = np.ones((4, 4))
print(matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Завдання 3

1. Створіть масив розміром 4x4, заповніть його випадковими цілими числами в діапазоні від 1 до 100 та виведіть його значення.

In [4]:
matrix = np.random.randint(1, 100, size=(4, 4))
print(matrix)

[[83 70 74  6]
 [23 17 56 59]
 [29 93 54  7]
 [21 99 77  7]]


Завдання 4

1. Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [5]:
matrix = np.random.random(size=(4, 4))

print(matrix)

[[0.18146716 0.67311013 0.38155139 0.7270616 ]
 [0.6219602  0.54173379 0.67454958 0.30382088]
 [0.41190207 0.36127427 0.25815632 0.05566169]
 [0.23775648 0.18250575 0.94154549 0.83258757]]


Завдання 5

1. Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.


In [6]:
vector1 = np.random.randint(1, 20, 6)
print(vector1)

vector2 = np.random.randint(1, 20, 6)
print(vector2)
print()

vector3 = vector1 + vector2
print(vector3)
vector4 = vector1 - vector2
print(vector4)
vector5 = vector1 * vector2
print(vector5)

[14  3 19 19 18 10]
[7 1 5 8 8 4]

[21  4 24 27 26 14]
[ 7  2 14 11 10  6]
[ 98   3  95 152 144  40]


Завдання 6
1.	Створіть два вектори розміром 5, заповніть їх довільними цілими числами та знайдіть їх скалярний добуток.

In [7]:
vector1 = np.random.randint(1, 20, 6)
print(vector1)

vector2 = np.random.randint(1, 20, 6)
print(vector2)
print()

s_dot = np.dot(vector1, vector2)
print(s_dot)

[ 2  5  6  4  4 18]
[ 9  7 14 18 11  3]

307


Завдання 7
1.	Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та перемножте їх між собою.

In [8]:
matrix_1 = np.random.randint(1, 20, size=(3, 2))
print(matrix_1)

matrix_2 = np.random.randint(1, 20, size=(2, 4))
print(matrix_2)
print()

new_matrix = np.dot(matrix_1, matrix_2)
print(new_matrix)


[[ 8  8]
 [ 3 19]
 [14 12]]
[[11  6 13 18]
 [ 5  9 11  5]]

[[128 120 192 184]
 [128 189 248 149]
 [214 192 314 312]]



Завдання 8
1.	Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 7 та знайдіть її обернену матрицю.

In [9]:
inverse_matrix = np.linalg.inv(matrix)
print(inverse_matrix)

[[ -1.53477556 -17.11957744  25.56079626   5.8785459 ]
 [  1.7913544   11.41254084 -15.30563399  -4.70563798]
 [ -0.08980823  14.32128948 -19.36102645  -3.85322007]
 [  0.14716636 -13.80840862  17.95055432   4.91134595]]


Завдання 9.
1.	Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [10]:
matrix = np.random.random((3, 3))
matrix

array([[0.58528149, 0.21625089, 0.47833495],
       [0.06363941, 0.34574888, 0.62091329],
       [0.70104618, 0.05181173, 0.9606239 ]])

Завдання 10
1.	Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть суму елементів отриманого вектору.

In [11]:
matrix = np.random.randint(1, 10, size=(3, 4))
print(matrix)

vector = np.random.randint(1, 10, size=4)
print(vector)

summ=np.sum(vector)
summ

[[4 8 4 3]
 [4 3 1 8]
 [5 3 1 4]]
[4 3 5 8]


20

Завдання 11
1.	Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [12]:
matrix = np.random.randint(1, 10, size=(2, 3))
print(matrix)

vector = np.random.randint(1, 10, size=3)
print(vector)

new_matrix=matrix*vector
new_matrix

[[6 5 8]
 [3 7 7]]
[1 7 5]


array([[ 6, 35, 40],
       [ 3, 49, 35]])

Завдання 12
1.	Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню суму.

In [13]:
matrix_1 = np.random.randint(1, 10, size=(2, 2))
print(matrix_1)

matrix_2 = np.random.randint(1, 10, size=(2, 2))
print(matrix_2)
print()

new_matrix = matrix_1 + matrix_2
print(new_matrix)

[[7 7]
 [7 1]]
[[7 2]
 [7 2]]

[[14  9]
 [14  3]]


Завдання 13
1.	Створіть дві матриці розміром 2x2, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть їх добуток.

In [14]:
matrix_1 = np.random.random(size=(2, 2))
print(matrix_1)

matrix_2 = np.random.random(size=(2, 2))
print(matrix_2)
print()

new_matrix = matrix_1 * matrix_2
print(new_matrix)

[[0.50861313 0.69851301]
 [0.6743217  0.99008783]]
[[0.9518036  0.84233525]
 [0.15200695 0.40656122]]

[[0.48409981 0.58838214]
 [0.10250158 0.40253132]]


Завдання 14
1.	Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть суму елементів матриці.

In [15]:
matrix = np.random.random(size=(5, 5))
print(matrix)

summ=np.sum(matrix)
summ

[[0.79109618 0.05800803 0.8583247  0.11758739 0.06027395]
 [0.65436002 0.73471813 0.24644813 0.8014947  0.62910439]
 [0.410311   0.8522169  0.34043117 0.9780644  0.62842349]
 [0.35264953 0.04109518 0.34797432 0.80073656 0.22975883]
 [0.6451793  0.21699689 0.83895484 0.75898989 0.76443818]]


13.157636099303305

Завдання 15
1.	Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [17]:
matrix = np.random.uniform(-1, 1, size=(5, 5))
print(matrix)

summ_row=np.sum(matrix, axis=1)
summ_row

[[-0.84895572 -0.72327878 -0.58018341  0.25733668 -0.69971292]
 [-0.05499754  0.6231549   0.17520162  0.03019588  0.01723386]
 [-0.17056897 -0.24296263  0.54497594  0.10847236 -0.00221032]
 [ 0.75784889 -0.28761194  0.97090769  0.00126007  0.94755741]
 [-0.837942   -0.93082666  0.5974256  -0.31172389 -0.82640006]]


array([-2.59479416,  0.79078872,  0.23770639,  2.38996212, -2.30946701])

Висновок: в цих завданнях були використані методи пакету numpy для роботи з векторами та матрицями, а також з діями між ними.